#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

HOST = data.get('host')
#This is specific to you module, so you need to change it accordingly.
# GET PENPOT SECRET KEY FROM ENVIROMENT
PENPOT_SECRET_KEY = os.getenv('PENPOT_SECRET_KEY')
PENPOT_PREPL_HOST="0.0.0.0"
PENPOT_PUBLIC_URI="https://"+HOST
PENPOT_REDIS_URI="redis://redis-app/0"
# EMAIL SETTINGS
rdb = agent.redis_connect(use_replica=True)
smtp_settings = agent.get_smarthost_settings(rdb)

PENPOT_SMTP_DEFAULT_FROM=smtp_settings['username']
PENPOT_SMTP_DEFAULT_REPLY_TO=smtp_settings['username']
PENPOT_SMTP_HOST=smtp_settings['host']
PENPOT_SMTP_PORT=smtp_settings['port']
PENPOT_SMTP_USERNAME=smtp_settings['username']
PENPOT_SMTP_PASSWORD=smtp_settings['password']
PENPOT_SMTP_TLS='true' if smtp_settings['tls_verify'] else 'false'

penpot_config = {
    "PENPOT_SECRET_KEY": PENPOT_SECRET_KEY,
    "PENPOT_PREPL_HOST": PENPOT_PREPL_HOST,
    "PENPOT_PUBLIC_URI": PENPOT_PUBLIC_URI,
    "PENPOT_REDIS_URI": PENPOT_REDIS_URI,
    "PENPOT_SMTP_DEFAULT_FROM": PENPOT_SMTP_DEFAULT_FROM,
    "PENPOT_SMTP_DEFAULT_REPLY_TO": PENPOT_SMTP_DEFAULT_REPLY_TO,
    "PENPOT_SMTP_HOST": PENPOT_SMTP_HOST,
    "PENPOT_SMTP_PORT": PENPOT_SMTP_PORT,
    "PENPOT_SMTP_USERNAME": PENPOT_SMTP_USERNAME,
    "PENPOT_SMTP_PASSWORD": PENPOT_SMTP_PASSWORD,
    "PENPOT_SMTP_TLS": PENPOT_SMTP_TLS
}
agent.write_envfile("penpot.env", penpot_config)
# just before starting systemd unit
#agent.dump_env()
